name: Test and Package project
on:
  pull_request:
  push:
    paths:
      - '**.clj'
      - '**.edn'
      - '**/ci.yaml'
    branches:
      - main
jobs:
  clojure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install OpenGL Libraries
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libegl1 libgl1
          version: 1.0

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          cli: 1.11.3.1463    # Clojure CLI based on tools.deps
          clj-kondo: 2024.08.01 # Clj-kondo

      - name: Cache clojure dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
          key: cljdeps-${{ hashFiles('deps.edn') }}
          restore-keys: cljdeps-

      - name: Run Unit tests
        run: clojure -M:test/unit

      - name: Run Integration tests
        run: clojure -M:test/integration

      - name: "Lint with clj-kondo"
        run: clj-kondo --lint deps.edn src

      - name: Package Clojure project
        run: clojure -T:build jar